km_test/clients/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.ClientsList.as_view(), name='client_list'),
    url(r'^(?P<pk>\d+)/$', views.ClientDetail.as_view(),
        name='client_detail'),
    url(r'^add/$', views.ClientAdd.as_view(), name='add_client'),
    url(r'^photo_poll/$', views.ClientsVote.as_view(), name='photo_poll'),
    url(r'^download/xlsx_list/$', views.ClientListDownload.as_view(),
        name='download_client_list'),
    url(r'^delete/(?P<pk>\d+)/$', views.ClientRemove.as_view(),
        name='delete_client'),
]

km_test/km_test/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('clients.urls', namespace='clients')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

km_test/clients/models.py
from django.db import models

from datetime import date
from uuid import uuid4
import os.path


def uuid_file_names(instance, filename):
    """
    Random name for uploaded files
    """
    file_ext = os.path.splitext(filename)[1]
    file_path = 'clients/photo'
    new_filename = os.path.join(file_path, uuid4().hex + file_ext)
    return new_filename


class Client(models.Model):
    """
    Hypothetical client of Hypothetical company
    """

    first_name = models.CharField(verbose_name='First name', max_length=100)
    last_name = models.CharField(verbose_name='Last name', max_length=100)
    birth_date = models.DateField(verbose_name='Date of birth')
    picture = models.ImageField(verbose_name='Photo',
                                upload_to=uuid_file_names,
                                blank=True)

    @property
    def age(self):
        """
        How many years person lived so far
        """
        now = date.today().timetuple()
        bd = self.birth_date.timetuple()
        lived = now.tm_year - bd.tm_year
        if now.tm_yday < bd.tm_yday:
            lived -= 1
        return lived

    @property
    def votes(self):
        """
        How many votes this client have
        """
        if not hasattr(self, 'poll'):
            return 0
        else:
            return self.poll.votes


class Poll(models.Model):
    """
    Poll for every person in clients
    """
    client = models.OneToOneField(Client,
                                  primary_key=True,
                                  on_delete=models.CASCADE)
    votes = models.IntegerField(verbose_name='Votes', default=0)

km_test/clients/views.py
from __future__ import absolute_import
from celery.result import AsyncResult

from django.conf import settings
from django.views import generic
from django.core.urlresolvers import reverse_lazy
from django.core.exceptions import SuspiciousOperation
from django.db.models import F
from django.db import IntegrityError, transaction
from django.http import HttpResponseRedirect, Http404, FileResponse, HttpResponseServerError

from .tasks import create_sheet
from .models import Client, Poll

import os.path
from uuid import uuid4


class ClientsList(generic.ListView):
    """
    All of them
    """
    model = Client
    template_name = 'clients/client_list.html'
    context_object_name = 'clients'
    ordering = 'last_name'
    _order_options = ['first_name', 'last_name', 'birth_date',
                      '-first_name', '-last_name', '-birth_date']

    def get_ordering(self):
        """
        Get ordering from request
        """
        ordering = self.request.GET.getlist('order')
        if ordering is not None:
            ordering = [i for i in ordering if i in self._order_options]
        if not ordering:
            ordering = self.ordering
        return ordering

    def get_queryset(self):
        """
        Filter queryset using get request parameters
        """
        queryset = super(ClientsList, self).get_queryset()
        first_name_filter = self.request.GET.get('first_name')
        last_name_filter = self.request.GET.get('last_name')
        if first_name_filter:
            queryset = queryset.filter(first_name__icontains=first_name_filter)
        if last_name_filter:
            queryset = queryset.filter(last_name__icontains=last_name_filter)
        return queryset

    def get_context_data(self, **kwargs):
        """
        Keep filter throught subsequent requests
        """
        context = super(ClientsList, self).get_context_data(**kwargs)
        context['first_name'] = self.request.GET.get('first_name', '')
        context['last_name'] = self.request.GET.get('last_name', '')
        return context


class ClientDetail(generic.DetailView):
    """
    All we know about it
    """
    model = Client
    template_name = 'clients/client_detail.html'
    context_object_name = 'client'


class ClientAdd(generic.CreateView):
    """
    Make a new one
    """
    model = Client
    template_name_suffix = '_add'
    fields = ['first_name', 'last_name', 'birth_date', 'picture']
    success_url = reverse_lazy('clients:client_list')


class ClientRemove(generic.DeleteView):
    """
    Get rid of some
    """
    model = Client
    template_name_suffix = '_delete'
    context_object_name = 'client'
    success_url = reverse_lazy('clients:client_list')


class ClientListDownload(generic.TemplateView):
    """
    All in one sheet
    """
    template_name = 'clients/download_client_list.html'
    tmp_file_path = settings.TEMP_FILE_PATH
    mime_type = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    downloaded_file_name = 'Client_list.xlsx'
    task = None

    def get_tmp_file_name(self):
        """
        UUID as a temporary file name
        """
        return os.path.join(self.tmp_file_path, uuid4().hex)

    def get(self, request, *args, **kwargs):
        """
        Generate new file and create new link to it
        """
        task_id = request.GET.get('download_id')
        if not task_id:
            self.task = create_sheet.delay(self.get_tmp_file_name()).id
        else:
            result = AsyncResult(task_id)
            if result.failed():
                return HttpResponseServerError('Some error occured')
            if result.ready():
                response = FileResponse(
                    open(result.result, 'rb'),
                    content_type=self.mime_type)
                response['Content-Disposition'] = (
                    'attachment; filename=%s' % self.downloaded_file_name)
                return response
            else:
                self.task = task_id

        return super(ClientListDownload, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """
        Add link to file
        """
        context = super(ClientListDownload, self).get_context_data(**kwargs)
        if self.task:
            context['file_id'] = self.task
        return context


class ClientsVote(generic.ListView):
    """
    Likes
    """
    template_name = 'clients/photo_poll.html'
    context_object_name = 'photo_list'
    queryset = Client.objects.exclude(picture='')
    http_method_names = ['get', 'post']
    _max_likes = 10

    @transaction.atomic
    def post(self, request):
        """
        Add like to a photo
        """
        photo_id = request.POST.get('vote')

        try:
            photo_id = int(photo_id)
        except (ValueError, TypeError):
            raise SuspiciousOperation

        try:
            client = Client.objects.get(id=photo_id)
        except Client.DoesNotExist:
            raise Http404('No such photo')

        if not hasattr(client, 'poll'):
            try:
                Poll(client=client).save(force_insert=True)
            except IntegrityError:
                pass

        Poll.objects.filter(
            client=client,
            votes__lt=self._max_likes
        ).select_for_update().update(votes=F('votes') + 1)
        return HttpResponseRedirect(reverse_lazy('clients:photo_poll'))

    def get_context_data(self, **kwargs):
        """
        Add likes limit to template
        """
        context = super(ClientsVote, self).get_context_data(**kwargs)
        context['max_likes'] = self._max_likes
        return context

km_test/clients/templates/clients/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'clients/style.css' %}"/>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

km_test/clients/templates/clients/client_add.html
{% extends 'clients/base.html' %}

{% block title %} New client {% endblock %}

{% block content %}
    <h1 class="header">New client</h1>

    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_ul }}
        <input type="submit" value="Create client">
    </form>
{% endblock %}

km_test/clients/templates/clients/client_delete.html
{% extends 'clients/base.html' %}

{% block title %} Photo poll {% endblock %}

{% block content %}
<h1 class="header">Delete</h1>

<p>You are going to remove</p>
<div>{{ client.first_name }} {{ client.last_name }}</div>

<form method="post">
    {% csrf_token %}
    <input type="submit" value="delete">
</form>

<a href="{% url 'clients:client_list' %}">Back to list</a>
{% endblock %}

km_test/clients/templates/clients/client_detail.html
{% extends 'clients/base.html' %}

{% block title %} Client details {% endblock %}

{% block content %}
    {% load static %}
    <h1 class="header">{{ client.first_name }} {{ client.last_name }}</h1>

    <div>
        {% if client.picture %}
            <img src="{{ client.picture.url }}"/>
        {% else %}
            <img src="{% static 'clients/no_photo.jpg' %}"/>
        {% endif %}
    </div>
    <div>{{ client.birth_date|date:"d.M.Y" }}</div>
    <div>{{ client.age }}</div>
    <div>
        <a href="{% url 'clients:delete_client' client.id %}">
            delete client
        </a>
    </div>
{% endblock %}

km_test/clients/templates/clients/client_list.html
{% extends 'clients/base.html' %}

{% block title %} List of clients {% endblock %}

{% block content %}
    {% load static %}
    <h1 class="header">Clients list</h1>

    <form id="sort_filter" method="get">
        <input type="text" name="first_name" value="{{ first_name }}">
        <input type="text" name="last_name" value="{{ last_name }}">
        <input type="submit" value="apply filter">
    </form>
    <table>
        <tr>
            <th>
                First name
                <button form="sort_filter" type="submit" name="order"
                        value="first_name">+
                </button>
                <button form="sort_filter" type="submit" name="order"
                        value="-first_name">-
                </button>
            </th>
            <th>
                Last name
                <button form="sort_filter" type="submit" name="order"
                        value="last_name">+
                </button>
                <button form="sort_filter" type="submit" name="order"
                        value="-last_name">-
                </button>
            </th>
            <th>
                Birth date
                <button form="sort_filter" type="submit" name="order"
                        value="birth_date">+
                </button>
                <button form="sort_filter" type="submit" name="order"
                        value="-birth_date">-
                </button>
            </th>
            <th>Age</th>
            <th>Photo</th>
        </tr>
        {% for client in clients %}
            <tr>
                <td>
                    <a href="{% url 'clients:client_detail' client.id %}">{{ client.first_name }}</a>
                </td>
                <td>
                    <a href="{% url 'clients:client_detail' client.id %}">{{ client.last_name }}</a>
                </td>
                <td>{{ client.birth_date|date:"d.M.Y" }}</td>
                <td>{{ client.age }}</td>
                <td>                    {% if client.picture %}
                    <img src="{{ client.picture.url }}"/>
                {% else %}
                    <img src="{% static 'clients/no_photo.jpg' %}"/>
                {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
    <div>
       <a href="{% url 'clients:add_client' %}">
            add new client
        </a>
    </div>
    <div>
        <a href="{% url 'clients:download_client_list' %}">
            download client list    
        </a>
    </div>
{% endblock %}

km_test/clients/templates/clients/download_client_list.html
{% extends 'clients/base.html' %}

{% block title %} Download {% endblock %}

{% block content %}

    <h1>List of clients in xlsx format</h1>

    <div>
        <span>Your results will be ready soon</span>
        <span>Try again later</span>
        <a href="{% url 'clients:download_client_list' %}?download_id={{ file_id }}">Check now</a>
    </div>
{% endblock %}

km_test/clients/templates/clients/photo_poll.html
{% extends 'clients/base.html' %}

{% block title %} Photo poll {% endblock %}

{% block content %}
    <h1 class="header">Like a photo</h1>

    <form id="like" method="post">
        {% csrf_token %}
    </form>
        {% for photo in photo_list %}
        <div>
            <img src="{{ photo.picture.url }}"/>
            <div>Likes:{{ photo.votes }}</div>
            {% if photo.votes < max_likes %}
            <button form="like" type="submit" name="vote" value="{{ photo.id }}">
                + 1
            </button>
            {% endif %}
        </div>
        {% endfor %}
{% endblock %}